import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#fff8f3',
        'surface-dim': '#dfd9d4',
        'surface-bright': '#fff8f3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f9f2ed',
        'surface-container': '#f3ede8',
        'surface-container-high': '#ede7e2',
        'surface-container-highest': '#e8e1dd',
        'on-surface': '#1d1b18',
        'on-surface-variant': '#4d463c',
        'inverse-surface': '#33302d',
        'inverse-on-surface': '#f6f0eb',
        outline: '#7e766b',
        'outline-variant': '#cfc5b8',
        'surface-tint': '#6e5c3c',
        primary: '#6e5c3c',
        'on-primary': '#ffffff',
        'primary-container': '#d0b892',
        'on-primary-container': '#59482a',
        'inverse-primary': '#dcc39c',
        secondary: '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e5e2e1',
        'on-secondary-container': '#656464',
        tertiary: '#5e5e5d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#bbbbb9',
        'on-tertiary-container': '#4a4b4a',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#f9dfb7',
        'primary-fixed-dim': '#dcc39c',
        'on-primary-fixed': '#261902',
        'on-primary-fixed-variant': '#554427',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1c1b1b',
        'on-secondary-fixed-variant': '#474646',
        'tertiary-fixed': '#e3e2e0',
        'tertiary-fixed-dim': '#c7c6c5',
        'on-tertiary-fixed': '#1a1c1b',
        'on-tertiary-fixed-variant': '#464746',
        background: '#fff8f3',
        'on-background': '#1d1b18',
        'surface-variant': '#e8e1dd',
        'ivory-bg': '#FCFAF7',
        'charcoal-text': '#1A1A1A',
        'gold-accent': '#D0B892',
        'muted-silver': '#868686',
        'soft-blue-gray': '#E2E9F2',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'base-unit': '8px',
        'container-max': '1280px',
        gutter: '24px',
        'section-padding-desktop': '120px',
        'section-padding-mobile': '64px',
        'section-desktop': '120px',
        'section-mobile': '64px',
      },
      fontFamily: {
        'display-lg': ['"Playfair Display"', 'serif'],
        'headline-lg': ['"Playfair Display"', 'serif'],
        'headline-lg-mobile': ['"Playfair Display"', 'serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        button: ['Inter', 'sans-serif'],
        'label-button': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '56px', fontWeight: '500' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        button: ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-button': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      screens: {
        sm: '375px',
        md: '768px',
        lg: '1024px',
        xl: '1440px',
      },
      animation: {
        float: 'float 8s ease-in-out infinite',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
